spring:
  profiles:
    active: dev # по умолчанию для разработки
cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "http://172.19.0.1:3000"
    - "http://172.19.0.1:3001"
    - "http://95.213.143.142"
    - "http://xn--24-mlcu7d.xn--p1ai"
